gantt
    dateFormat  YYYY-MM-DD
    title       Project Plan
    excludes    weekends, tuesday
    axisFormat  Week %W
    tickInterval 1week
    todayMarker off
    weekday monday


    section Simulation Environment
    Verilator Wrapper : backend, 2024-10-03, 5d
    Concurrency support : conc, after backend, 5d


    section Testbench Methodology
    Define Phases: 5d
    Define class hierarchy :  6d


    section Report
    Technical background: 2024-10-07, 2w
    Finalizing: 2024-12-15, 2025-02-02