gantt
    dateFormat  YYYY-MM-DD
    excludes    weekends, tuesday
    axisFormat  %b %d
    tickInterval 1week
    todayMarker off
    weekday monday


    section Simulation Environment
    Verilator wrapper implementation: ver_wrap, 2024-10-03, 3d
    Scala wrapper implementation: sc_wrap, after ver_wrap, 3d
    Concurrency exploration : conc_expl, after sc_wrap, 3d
    Concurrency implementation : conc_impl, after conc_expl, 3d


    section Testbench Methodology
    Design class hierarchy: 4d
    Decide simulation phases :  1d
    Design utilities and APIs : 2d
    Design testbench API: 3d
    Design RAL API : 3d
    Implement base classes and utilities: 8d
    Implement testbench API: 4d
    Implement RAL : 3d
    Buffer : 8d

    section Report
    Write technical background: 2024-10-07, 2w
    Finalize Report: 2024-12-15, 2025-02-02